markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Ainom
description: Ainom
keywords: Ainom
url: http://www.ainom.com
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: Ainom
    email: javamickey@163.com
    imageLink: ./image/picture.jpg
    simpleIntro: Ainom 爱码农，更爱生活！
    detailIntro:
      <p>Ainom，毕业于沙坡村皇家职业技术学院。小硕一枚。</p>
      <p>爱生活，更爱小四。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/Javamickey
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/Javamickey
  - class: icon-twitter
    url: http://twitter.com/Javamickey
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: Ainom
      url: http://www.ainom.com
      text: Bonnshore
      url: http://www.bonnshore.com
      text: Spiderfan
      url: http://www.spiderfan.cn
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: Ainom